In [5]:
import pandas as pd

In [6]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/' 
url = f'{prefix}yellow_tripdata_2020-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-01.csv.gz'

In [7]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [8]:
len(df)

6405008

In [ ]:
df['VendorID']

In [ ]:
df.dtypes

In [ ]:
df.shape

In [9]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2020-01-01 00:28:15,2020-01-01 00:33:03,1,1.2,1,N,238,239,1,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1,2020-01-01 00:35:39,2020-01-01 00:43:04,1,1.2,1,N,239,238,1,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1,2020-01-01 00:47:41,2020-01-01 00:53:52,1,0.6,1,N,238,238,1,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1,2020-01-01 00:55:23,2020-01-01 01:00:14,1,0.8,1,N,238,151,1,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2,2020-01-01 00:01:58,2020-01-01 00:04:16,1,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0

In [10]:
df['tpep_pickup_datetime']

0         2020-01-01 00:28:15
1         2020-01-01 00:35:39
2         2020-01-01 00:47:41
3         2020-01-01 00:55:23
4         2020-01-01 00:01:58
                  ...
6405003   2020-01-31 22:51:00
6405004   2020-01-31 22:10:00
6405005   2020-01-31 22:50:07
6405006   2020-01-31 22:25:53
6405007   2020-01-31 22:44:00
Name: tpep_pickup_datetime, Length: 6405008, dtype: datetime64[us]

In [11]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [ ]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

In [24]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [25]:
from tqdm.auto import tqdm

In [26]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [15]:
df = next(df_iter)

In [16]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2020-01-01 00:28:15,2020-01-01 00:33:03,1,1.2,1,N,238,239,1,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1,2020-01-01 00:35:39,2020-01-01 00:43:04,1,1.2,1,N,239,238,1,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1,2020-01-01 00:47:41,2020-01-01 00:53:52,1,0.6,1,N,238,238,1,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1,2020-01-01 00:55:23,2020-01-01 01:00:14,1,0.8,1,N,238,151,1,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2,2020-01-01 00:01:58,2020-01-01 00:04:16,1,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2020-01-01 14:08:46,2020-01-01 14:19:08,3,1.7,1,N,186,162,2,9.0,2.5,0.5,0.00,0.0,0.3,12.30,2.5
99996,1,2020-01-01 14:21:39,2020-01-01 14:25:46,2,0.9,1,N,229,141,1,5.0,2.5,0.5,1.65,0.0,0.3,9.95,2.5
99997,1,2020-01-01 14:38:26,2020-01-01 14:42:29,1,0.8,1,N,263,75,1,5.0,2.5,0.5,0.83,0.0,0.3,9.13,2.5
99998,1,2020-01-01 14:48:55,2020-01-01 14:58:39,1,1.4,1,N,236,161,1,9.0,2.5,0.5,1.70,0.0,0.3,14.00,2.5
99999,1,2020-01-01 14:19:07,2020-01-01 14:36:15,1,12.5,1,N,132,64,1,34.5,0.0,0.5,7.05,0.0,0.3,42.35,0.0